---
- name: Remove apache deployment
  hosts: server2
  vars:
    web_pkg: httpd
    web_service: httpd
    firewall_service: firewalld
    rule: http

  tasks:
    - name: Stop and disable web service
      ansible.builtin.service:
        name: "{{ web_service }}"
        enabled: false
        state: stopped

    - name: Remove web package
      ansible.builtin.dnf:
        name: "{{ web_pkg }}"
        state: absent

    - name: Remove index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Ensure firewall is running
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        enabled: true
        state: started

    - name: Remove firewall rule for web service
      ansible.posix.firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: disabled